name: Taller 4
favicon: null
layout_spectrum: 0.23945
typography_spectrum: 0.46411
title: T4 v2016
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fc4f46'
    - '#ffffff'
    - '#000000'
    - '#fdaba6'
    - '#6f231e'
  brandStrength: 0.7834153873845935
  lightness: 0.8125
  saturation: 0.375
  rhythmicContrast: 0.20848898007534444
purpose: []
