name: Taller 4
favicon: null
layout_spectrum: 0.23945
typography_spectrum: 0.49454
title: T4 v2016
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fc4f46'
    - '#ffffff'
    - '#000000'
    - '#fdaba6'
    - '#6f231e'
  brandStrength: 0.5
  lightness: 0.5625
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
